### ISSUE TITLE
ERROR when run command 'just install-dependencies'

### ISSUE THREAD

**Issue by rucjrliu** [sfu-db/AreCELearnedYet#1]
error: Non-default parameter 'old_new_file' follows default parameter

690 | report-error-dynamic dataset='census13' old_new_file new_new_file T update_time:

![AreCELearnedYet_ERROR](https://user-images.githubusercontent.com/35796808/103227574-a5622b00-4969-11eb-951b-50caa37fea2f.PNG)

PS: My environment:
Ubuntu16.04
conda

**Comment by dovahcrow** [comment]
Hi @rucjrliu  I pushed a fix can you pull again and have a try?

**Comment by rucjrliu** [comment]
@dovahcrow It seems OK now. Thanks.
![AreCELearnedYet_ERROR_OK](https://user-images.githubusercontent.com/35796808/103253738-5fcf4d80-49bd-11eb-9213-3d8a6b99c62c.PNG)
