### ISSUE TITLE
just install-dependencies failed.

### ISSUE THREAD

**Issue by Doris404** [sfu-db/AreCELearnedYet#4]
<img width="720" alt="截屏2021-11-11 下午2 51 31" src="https://user-images.githubusercontent.com/37341760/141251581-93e4a72b-69b5-4642-87dc-4e45db633fe6.png">

When running  `just install-dependencies`,  the install of gpustat==0.6.0 failed. My python version is 3.8.12, my poetry version is 1.1.11.

**Comment by wangxiaoying** [comment]
Hi @Doris404 ,

I tried python 3.8.12 on my machine and the dependencies can be successfully installed.

I'm not sure why `gpustat` cannot be installed in your environment, but it seems like `gpustat` is only a soft dependency of `ray` and they are considering removing this according to this issue: https://github.com/ray-project/ray/issues/15700 . So I think it should be fine without having this package installed to run our code. A workaround might be use `pip install --no-dependencies ray` to manually install ray as mentioned in the issue and remove this from the dependency.
