### ISSUE TITLE
If I don't have an Nvidia graphics card on my machine, Can I run all the tests?

### ISSUE THREAD

**Issue by wtsclwq** [sfu-db/AreCELearnedYet#6]
This probably means I can't use the GPU to speed up my calculations，It is my environment：

![image](https://user-images.githubusercontent.com/37504557/188203181-bd00159e-837c-450c-8fd9-91cfd613000f.png)

**Comment by wangxiaoying** [comment]
Hi @wtsclwq , our experiments should be able to run on CPU.
